import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Hill Song</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="fav.jpg"  />
      </Head>

      <Navbar />
      <Footer />

    </div>
  )
}
